import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => fs.readFileSync(path.join(root, 'rag/sources', file), 'utf8').replace(/^\uFEFF/, '');
const chunks = [];
const add = (source, section, text) => {
  text = text.trim();
  if (!text) return;
  const paragraphs = text.split(/\n\s*\n/);
  let buffer = '';
  const emit = () => {
    if (buffer.trim()) chunks.push({ ...source, section, text: buffer.trim(), id: `${source.key}-${chunks.length + 1}` });
    buffer = '';
  };
  for (const paragraph of paragraphs) {
    // Split long blocks by lines so project or employer descriptions stay together.
    for (const part of paragraph.length > 1400 ? paragraph.split('\n') : [paragraph]) {
      if (buffer.length + part.length > 1400) emit();
      buffer += `${part}\n`;
    }
    buffer += '\n';
  }
  emit();
};
const resume = JSON.parse(read('resume.json'));
for (const entry of resume.sections) {
  const topic = { CONTACT: 'contact', SUMMARY: 'overview', SKILLS: 'skills', EXPERIENCE: 'experience', PROJECTS: 'projects', EDUCATION: 'education', ACHIEVEMENTS: 'achievements', CERTIFICATIONS: 'certifications' }[entry.section];
  const source = { key: 'resume', title: "Rajat's resume", url: `/assets/docs/Rajat_Krishnan_Resume.pdf#page=${entry.page}`, kind: 'resume', topic, hash: resume.sha256 };
  if (topic === 'projects' || topic === 'experience') {
    const starts = topic === 'projects' ? /^(PrepPeer:|GridWatch:|Bitcoin Sentiment Analysis$|University Event Management System$)/ : /^(AI Fluency Intern,|Freelance AI Content Developer)/;
    let block = [], label = '';
    for (const line of entry.text.split('\n')) {
      if (starts.test(line)) {
        if (block.length) add({ ...source, entity: label }, label, block.join('\n'));
        label = line.split(':')[0]; block = [];
      }
      block.push(line);
    }
    if (block.length) add({ ...source, entity: label }, label, block.join('\n'));
  } else add(source, entry.section, entry.text);
}
const documents = [
  { key: 'PrepPeer', entity: 'PrepPeer', allow: /^(overview|stack)$/i },
  { key: 'gridwatch', entity: 'GridWatch', allow: /overview|how to demo|file structure/i },
  { key: 'NextStep-2', entity: 'NextStep.AI', allow: /^(overview|tech stack|user roles)$/i },
  { key: 'university-event-management-system', entity: 'University Event Management System', allow: /overview|features|students|organizers|administrators|real.time|architecture/i },
  { key: 'bitcoin-sentiment-analysis', entity: 'Bitcoin Sentiment Analysis', allow: /^(overview|what is covered|data)$/i },
  { key: 'ZedWorks-portfolio', entity: 'ZedWorks', allow: /overview|about zedworks|tools.*skills|featured projects|pent/i }
];
for (const doc of documents) {
  const markdown = read(`${doc.key}.md`);
  const meta = JSON.parse(read(`${doc.key}.meta.json`));
  const source = { key: doc.key, entity: doc.entity, kind: 'project', topic: 'projects', title: `${doc.entity} documentation`, url: meta.html_url, hash: crypto.createHash('sha256').update(markdown).digest('hex'), gitBlob: meta.sha };
  let section = 'Overview', lines = [], inFence = false;
  const flush = () => {
    if (doc.allow.test(section)) add(source, section, lines.join('\n').replace(/\*\*/g, '').replace(/\[([^\]]+)\]\([^)]*\)/g, '$1'));
    lines = [];
  };
  for (const line of markdown.split('\n')) {
    if (line.trim().startsWith('```')) { inFence = !inFence; continue; }
    if (inFence && !/architecture|file structure/i.test(section)) continue;
    const heading = line.match(/^(#{1,6})\s+(.+)/);
    if (heading && heading[1].length > 1) { flush(); section = heading[2].replace(/[^\p{L}\p{N}\s&.-]/gu, '').trim(); }
    else if ((!heading || heading[1].length === 1) && !/^\s*---\s*$/.test(line)) lines.push(heading ? heading[2] : line);
  }
  flush();
}
// These are current, public owner statements; no inferred semester, birth date or private details.
add({ key: 'portfolio', kind: 'owner', topic: 'availability', title: 'Portfolio — availability', url: 'https://rajat77a.github.io/#home' }, 'Availability', 'Rajat Krishnan is open to internships, AI product work, and product engineering roles. He is interested in prompt engineering, AI products, full-stack development, automation, and data tools.');
add({ key: 'portfolio', kind: 'owner', topic: 'education', title: 'Portfolio — about', url: 'https://rajat77a.github.io/#about' }, 'Current studies', 'Rajat Krishnan describes himself as a third-year Integrated M.Tech CSE student at VIT-AP (2024–2029).');
const output = { version: 1, chunks };
fs.writeFileSync(path.join(root, 'rag/index.js'), `// Generated by scripts/build-rag.mjs. Do not edit manually.\nexport default ${JSON.stringify(output, null, 2)};\n`);
console.log(`Indexed ${chunks.length} passages from the resume, 6 project READMEs, and public owner statements.`);
